### ISSUE TITLE
don't depend on a specific http client

### ISSUE THREAD

**Issue by videni** [cristian-sima/redux-paginator-immutable#23]
hi, I am using axios in my project a a lot, even though we can use superagent and axios together, but it complicate our project, can we don't depend on superagent, let the developer choose which http client he wants?

**Comment by cristian-sima** [comment]
Hi @videni and thank you for your problem. I will reflect about it and come with a solutio. In case you have one, please create a pull request

**Comment by cristian-sima** [comment]
@videni is still this issue available?

**Comment by cristian-sima** [comment]
The solution is to create a folk and use the desired http.
